Soal 1

In [1]:
import numpy as np

In [4]:
x = np.array([[25, 15, 61], [47, 23, 4]])
x # buat matrix X berukuran 2x3 menggunakan numpy

array([[25, 15, 61],
       [47, 23,  4]])

In [5]:
x.shape # tampilkan ukuran dari matrix x

(2, 3)

In [8]:
x[:,0] # tampilkan seluruh elemen dari kolom pertama dari matrix x

array([25, 47])

In [9]:
x[:,1] # tampilkan seluruh elemen dari baris kedua dari matrix x

array([15, 23])

Soal 2

ulangi soal nomor 1 menggunakan pytorch

In [21]:
import torch

In [22]:
x_pt = torch.tensor([[25, 15, 61], [47, 23, 4]])
x_pt

In [23]:
x_pt.shape

torch.Size([2, 3])

In [24]:
x_pt[:,0]

tensor([25, 47])

In [25]:
x_pt[:,1]

tensor([15, 23])

ulangi soal nomor 1 menggunakan tensorflow

In [2]:
import tensorflow as tf

In [20]:
x_tf = tf.Variable([[25, 15, 61], [47, 23, 4]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 15, 61],
       [47, 23,  4]], dtype=int32)>

In [21]:
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [22]:
x_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([25, 47], dtype=int32)>

In [23]:
x_tf[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([15, 23], dtype=int32)>