Soal 1

In [ ]:
import numpy as np

In [ ]:
x = np.array([25,61,47]) # buat vector x dengan ukuran 3x1
x

array([25, 61, 47])

In [ ]:
len(x) # Hitung panjang vector x

3

In [ ]:
x.shape # Tampilkan ukuran vector x

(3,)

In [ ]:
type(x) # Tampilkan tipe data dari vector

numpy.ndarray

In [ ]:
x[0] # Akses elemen pertma dari vector x

np.int64(25)

In [ ]:
type (x[0]) # Tampilkan tipe data elemen pertama dari vector x

numpy.int64

Soal 2

In [ ]:
x_t = x.T # lakukan transpose pada vector x dan simpan pada variabel x_t
x_t

array([25, 61, 47])

In [ ]:
x_t.shape # tampilkan ukuran dari vector x_t

(3,)

In [ ]:
y = np.array([[25, 61, 47]]) # lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y
y_t

array([[25, 61, 47]])

In [ ]:
y_t.shape # tampilkan ukuran dari vector x_t

(1, 3)

Soal 3 lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [ ]:
import torch
import tensorflow as tf

In [ ]:
x_pt = torch.tensor([25, 61, 47])
x_pt

tensor([25, 61, 47])

In [ ]:
x_tf = tf.Variable([25, 61, 47])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25, 61, 47], dtype=int32)>